version: '3'
services:
  redis:
    container_name: lanb-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  mysql:
    container_name: lanb-mysql
    build: ./mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
  app:
    container_name: lanb-wvs-be
    build: ./lanb-wvs-be
    ports:
      - "1234:1234"
    depends_on:
      - mysql
      - redis
  nginx:
    container_name: lanb-nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

#失败删除
#docker stop `docker ps -a | grep lanbwvs | awk '{print $1}'`
#docker rm `docker ps -a | grep lanbwvs | awk '{print $1}'`
#docker rmi `docker images | grep lanbwvs | awk '{print $1}'`